version: '1.0'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  python-app:
    image: python:3.11-slim
    container_name: slim-python
    depends_on:
      - redis
    networks:
      - app-network
    command: tail -f /dev/null

networks:
  app-network:
    driver: bridge

