services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-python
    depends_on:
      - redis
    networks:
      - app-network
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_CONFIG=configs/app.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: tail -f /dev/null
    stdin_open: true        # <─ keeps STDIN open
    tty: true               # <─ allocate a TTY
    

networks:
  app-network:
    driver: bridge