services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-python
    depends_on:
      - redis
    networks:
      - app-network
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true        # <─ keeps STDIN open
    tty: true               # <─ allocate a TTY
    command: tail -f /dev/null

networks:
  app-network:
    driver: bridge