redis:
  host: redis
  port: 6379

channels:
  defaults: ["general"]

ollama:
  base_url: http://host.docker.internal:11434
  bots:
    BOT1:
      model: gemma3:4b
      generation_config:
        temperature: 0.7
        top_p: 0.95
        num_predict: 300
        # stop: ["/shutdown"]
    BOT2:
      model: gemma3:4b
      generation_config:
        temperature: 0.7
        top_p: 0.9
        num_predict: 300
        # stop: ["/shutdown"]
        
channel_turns:
  general:
    initial_bot: BOT2

cli:
  prompt_prefix: "\n> "

message:
  from: "system"
  body: "Discuss current issues surrounding rare earth metals."

prompts:
  BOT1: Respond to the most recent message while keeping your responses concise and focused.
  BOT2: Respond to the most recent message while keeping your responses concise and focused.
