channel: "general"

message:
  from: "system"
  body: "Discuss current issues surrounding rare earth metals."

prompts:
  BOT1: >
      Keep your messages concise and focused.
  BOT2: >
      Keep your messages concise and focused.
